create schema isi;

drop table isi.facts;

create table isi.facts (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	OBJECT_A VARCHAR(100) NOT NULL,
	OBJECT_B VARCHAR(100) NOT NULL,
	RELATION VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
);
